tk1351/qaz

- vite.config.ts
> Vite の設定追加

- .eslintrc.cjs
- package-lock.json
- package.json
- prettier.config.cjs
- src/App.tsx
- src/main.tsx
- eslintの設定
- ルールは xo 準拠
- prettierの設定
> eslint, prettier 設定

- .eslintrc.cjs
- package-lock.json
- package.json
- src/components/atoms/Header/Header.stories.tsx
- src/components/atoms/Header/Header.test.tsx
- src/components/atoms/Header/Header.tsx
- src/features/add.test.ts
- src/features/add.ts
- tsconfig.json
- vite.config.ts
- vitest.setup.ts
- vitest の設定
- react-testing-library の設定
- eslint のオーバーライド設定
> Vitest, react-testing-library 設定

- data/tokens.json
- Figma Tokens から json ファイルを生成
- 参考: https://zenn.dev/mi_/articles/453f7594120c9a#%F0%9F%91%A9%E2%80%8D%F0%9F%92%BB-figma-tokens-%E3%81%A8-github-%E3%83%AA%E3%83%9D%E3%82%B8%E3%83%88%E3%83%AA%E3%82%92%E9%80%A3%E6%90%BA%E3%81%99%E3%82%8B
> Figma Tokens から json ファイルを生成

- data/build/_variables.css
- package-lock.json
- package.json
- sd.config.js
- style dictionary インストール
- token.json から _variables.css を生成
> style-dictionaryでカラーファイル生成

- data/tokens.json
- Figma Tokens の Text Color 追加
> Figma Tokens の Text Color 追加

- data/build/_variables.css
- data/build/tokens.d.ts
- data/build/tokens.js
- src/App.tsx
- Header へスタイル追加
- Style Dictionary のファイル生成変更
> Header へスタイル追加

- src/App.tsx
- src/constants/navigation.ts
- src/features/add.test.ts
- src/features/add.ts
- src/features/convertToUpperCase.test.ts
- src/features/convertToUpperCase.ts
- 文字列を大文字へ変換する関数作成
- `App.tsx` へ適用
- Navigation Link 用の定数ファイル作成
> 文字列を大文字へ変換する関数作成

- src/components/atoms/HeroImage/HeroImage.stories.tsx
- src/components/atoms/HeroImage/HeroImage.tsx
> feat: add HeroImage

- src/components/atoms/Stack/Stack.stories.tsx
- src/components/atoms/Stack/Stack.tsx
> Stack コンポーネント作成

- src/components/atoms/Cluster/Cluster.stories.tsx
- src/components/atoms/Cluster/Cluster.tsx
> Cluster コンポーネントの作成

- src/components/atoms/Grid/Grid.stories.tsx
- src/components/atoms/Grid/Grid.tsx
> Grid Component の作成

- src/components/atoms/ProfileCard/ProfileCard.stories.tsx
- src/components/atoms/ProfileCard/ProfileCard.test.tsx
- src/components/atoms/ProfileCard/ProfileCard.tsx
- ProfileCard コンポーネントの作成
- テスト記述
> feat: add profile-card component

- src/components/atoms/MovieCard/MovieCard.tsx
> MovieCard コンポーネントから any を削除

- src/components/commons/MovieList/MovieList.stories.tsx
- src/components/commons/MovieList/MovieList.test.tsx
- src/components/commons/MovieList/MovieList.tsx
- src/shared/types/index.ts
> MovieList コンポーネントの作成

- src/components/atoms/IconButton/IconButton.stories.tsx
- src/components/atoms/IconButton/IconButton.test.tsx
- src/components/atoms/IconButton/IconButton.tsx
- IconButton へ disabled 追加
- テスト追加
> IconButton へ disabled 追加

- src/components/commons/ProfileList/ProfileList.stories.tsx
- src/components/commons/ProfileList/ProfileList.test.tsx
- src/components/commons/ProfileList/ProfileList.tsx
- src/shared/types/index.ts
- ProfileList コンポーネントの作成
- テスト追加
> ProfileList コンポーネントの作成

- src/components/commons/MovieDescription/MovieDescription.stories.tsx
- src/components/commons/MovieDescription/MovieDescription.test.tsx
- src/components/commons/MovieDescription/MovieDescription.tsx
- MovieDescription コンポーネントの作成
- テスト追加
> MovieDescription コンポーネントの作成

- src/components/commons/MovieSynopsis/MovieSynopsis.stories.tsx
- src/components/commons/MovieSynopsis/MovieSynopsis.test.tsx
- src/components/commons/MovieSynopsis/MovieSynopsis.tsx
- MovieSynopsis コンポーネントの作成
- テスト追加
> MovieSynopsis コンポーネントの作成

- src/components/atoms/MovieCard/MovieCard.test.tsx
- src/components/atoms/ProfileCard/ProfileCard.test.tsx
> fix: remove setup

- package-lock.json
- package.json
- src/App.tsx
- src/constants/navigation.ts
- React Location 追加
- Header へ Link コンポーネント追加
> React Location 追加

- .gitignore
- api/index.ts
- api/types/index.ts
- api/types/movies.ts
- api/types/people.ts
- api/types/search.ts
- package-lock.json
- package.json
- src/App.tsx
- src/api/index.ts
- TMDB API の型定義
- react-query のインストール、設定
- aspida は一旦削除予定
> react-query の設定

- src/App.tsx
- src/components/atoms/Header/Header.tsx
- Header コンポーネントを App.tsx から切り出し
> Header コンポーネント切り出し

- src/App.tsx
- src/components/atoms/MovieCard/MovieCard.stories.tsx
- src/components/atoms/MovieCard/MovieCard.tsx
- src/components/commons/MovieList/MovieList.stories.tsx
- src/components/commons/MovieList/MovieList.tsx
- src/components/pages/Home/Home.tsx
- src/features/api/movie.ts
- src/features/excludeFromString.test.ts
- src/features/excludeFromString.ts
- src/routes/index.ts
- src/routes/index.tsx
> Home ページ作成

- api/types/people.ts
- src/components/atoms/Cluster/Cluster.tsx
- src/components/atoms/ProfileCard/ProfileCard.tsx
- src/components/pages/ProfileDetail/ProfileDetail.tsx
- src/features/api/people.ts
- src/routes/index.tsx
> プロフィール詳細ページの作成
